### ISSUE TITLE
Display suggested solution when trainer/timer is stopped?

### ISSUE THREAD

**Issue by dunkOnIT** [ngerritsen/timiks#11]
Especially for learning new cases, it could be useful to have information relating to the case which was just tested displayed when the timer is stopped. This could include:

- Name of case
- Suggested algorithms

You could even just display the information in "show info" below the stopped timer. This wouldn't be helpful to all users, though, so perhaps have the option to toggle this in the settings?

**Comment by ngerritsen** [comment]
I think this request can be phrased as "showing the previous case" in the trainer. I think that is a useful feature, just gonna think about how to show it nicely design wise.

**Comment by ngerritsen** [comment]
<img width="791" alt="Screenshot 2019-07-27 at 16 40 31" src="https://user-images.githubusercontent.com/6407496/61996050-4b807600-b090-11e9-912d-b66f58db7e7c.png">

I think this feature will suit your needs. When you click on the case it opens more details, including algs, name and probability.  It also allows you to Retry the case.

**Comment by dunkOnIT** [comment]
This looks perfect! Will try it out tomorrow - thanks so much :D
