### ISSUE TITLE
Multi-phase timer

### ISSUE THREAD

**Issue by dunkOnIT** [ngerritsen/timiks#13]
CsTimer has an option to set "multi-phase" timer in their settings. This is the amount of times the space bar needs to be hit before the timer stops. 

The default value is 1, and setting a value of 4 would allow the user to time their splits for a CFOP solve if they hit the spacebar after each stage of the solve.

**Comment by ngerritsen** [comment]
I will keep it in my mind, but I'm not sure when to implement it yet. :)
