### ISSUE TITLE
Display glitch when trainer times exceed width of table

### ISSUE THREAD

**Issue by dunkOnIT** [ngerritsen/timiks#14]
See the last line of the below image - there are more times for Gd than there is space on the line, leading to a visual glitch at the end of the table.

![image](https://user-images.githubusercontent.com/52967253/61358162-041d0d00-a87a-11e9-9cd1-efcfa931b265.png)

**Comment by ngerritsen** [comment]
What is the browser you are using, and do you still have this problem?
