### ISSUE TITLE
Can't load trainer page because of fatal code error

### ISSUE THREAD

**Issue by YTCuber** [ngerritsen/timiks#15]
I'm getting this error:
https://imgur.com/a/4xu3eE7
when loading the /trainer page in Firefox on Ubuntu Linux. My ad blocker is disabled and I don't have any extensions altering Javascript behaviour, only blocking of google analytics.

**Comment by ngerritsen** [comment]
Are you still having this issue?

**Comment by YTCuber** [comment]
Yes, only the file names changed a bit

**Comment by ngerritsen** [comment]
> Yes, only the file names changed a bit

Could you verify if it works in a private tab? I think it must be some old format of trainer times still in your browser's storage, early adopter.
