### ISSUE TITLE
Option to fix the y axis scale of the graph

### ISSUE THREAD

**Issue by Jobarion** [ngerritsen/timiks#16]
When switching off certain lines in the graph (especially "single"), the scale of the y axis changes. 
The option to fix the scale of the graph to the one used when all lines are shown would be helpful.

**Comment by ngerritsen** [comment]
This is currently the behaviour of the graph component I am using. Can you explain why this would be helpful? I think more detail is better right?

**Comment by Jobarion** [comment]
I think it's harder to see the overall trends if its zoomed in too much. The different zoom levels depending on the selected lines just feel visually co fusing.

**Comment by ngerritsen** [comment]
<img width="762" alt="Screenshot 2019-07-27 at 17 21 51" src="https://user-images.githubusercontent.com/6407496/61996277-fc881000-b092-11e9-8a3e-e8d67e40a052.png">
<img width="577" alt="Screenshot 2019-07-27 at 17 21 34" src="https://user-images.githubusercontent.com/6407496/61996278-fc881000-b092-11e9-84e2-a11148a1de4a.png">

I added the option to fix the y-axis of the graph. Might also add it later for the X-axis (to un-fix it). Thanks for the feedback 🙂.
