### ISSUE TITLE
Ability to unarchive solves/ ability to import without automatically archiving.

### ISSUE THREAD

**Issue by ghost** [ngerritsen/timiks#17]
Its useful because I want to import my cstimer times yet all my solves get archived and I can't undo that. I don't understand why archiving even exists

**Comment by ngerritsen** [comment]
Archiving exists to keep your session clean and have a different UI for analyzing the history of your solves. It will also make sure my database costs don't go up too much :). The idea is that you do a session and then archive them. Why do you want your solves to be in the active session? Unarchiving archived times could still be something I can do btw.

**Comment by ghost** [comment]
Oh I see it now. I do a couple then archive em. I didn't think that way before though.

 I was concerned that I couldn't see stats for my 1200 solves and was only focusing on the active tab stats graph. Thanks for pointing this out! I guess I was too familiar w cstimer.
