### ISSUE TITLE
Stats Graph might be better displaying larger aoX on the front layer

### ISSUE THREAD

**Issue by ghost** [ngerritsen/timiks#18]
The ao100 seems to be at the utmost back. Since the 'single' line and such are the most obtrusive, they should be at the back and larger averages such as ao100 and ao200 should be at the front.

**Comment by ngerritsen** [comment]
Nice idea, i'll try it :)

**Comment by ngerritsen** [comment]
Okay, I applied it and I think it is indeed a lot better :) thanks for the suggestion.

![Screenshot 2019-07-24 at 13 14 25](https://user-images.githubusercontent.com/6407496/61789442-0270bd80-ae15-11e9-9899-38e5823c5ba5.png)

**Comment by ghost** [comment]
Also, a little idea: maybe brighter colours would suit the front lines?

**Comment by ghost** [comment]
The purple especially
