### ISSUE TITLE
Issue with the scroll fade

### ISSUE THREAD

**Issue by kluckyklucky** [ngerritsen/timiks#19]
The scroll fade stays on the same time when you scroll past it, making the time hard to read, and making the scroll fade not always appear at the end

**Comment by kluckyklucky** [comment]
![Screenshot 2019-07-23 at 14 01 19](https://user-images.githubusercontent.com/32513432/61739660-7eee9800-ad52-11e9-9858-f84cf2e109fa.png)
Here's a picture

**Comment by ngerritsen** [comment]
Thanks, i'll take a look!

**Comment by ngerritsen** [comment]
It should be fixed now.
