### ISSUE TITLE
Add the ability to chose a default time period for the X-axis of the archive graph

### ISSUE THREAD

**Issue by geoffcampnell64** [ngerritsen/timiks#22]
Hey Niels,

I love using the Timiks timer, and I've found it to be much easier to use than many of the other browser-based timers. You've really done a great job building an intuitive system that looks great while retaining all of the powerful features users have come to expect. 

One feature that I wish was integrated is the ability to chose the default time scale on the x-axis of the archive graph. It is currently set at 7 days, and I change it every time I navigate to the archive page. In my opinion, 7 days is just too short of a time period to feel motivating, whereas 14 days or 30 days is quite a bit more motivating.

Thanks so much for making such a polished piece of free software, I hope you have a great day!

Regards,

Geoff

**Comment by ngerritsen** [comment]
Hey, thanks for the feedback. The reason the current default is 7 days is actually for cost technical reasons. The database I use charges per read, so the more times I initially show to users the more reads I use. I have 50k free reads per day so I want to stay below that. I can try increasing it to 14 and see how that goes though.
