### ISSUE TITLE
Feature Request: Sub-profiles for other cubes (2x2, 4x4, 3x3, etc)

### ISSUE THREAD

**Issue by Valien** [ngerritsen/timiks#23]
Love Timiks. Use it for 3x3 all the time. Leaning 2x2 now and would love to have it's own data set. Any chance when picking a different cube scramble that it generates a profile for it's solved data?

**Comment by ngerritsen** [comment]
When you archive your solves they will be separated under the type of puzzle. The session is just meant as a temporary list. The idea is that you do some solves and then archive. In the archive you can analyze your progression. However, it might be an idea to also separate them at the current session level. Not sure.

**Comment by Valien** [comment]
oh! hah, had no idea. Thanks so much. Will try that then!

**Comment by ngerritsen** [comment]
I implemented having the current session split per puzzle, let's see how that goes :)
