### ISSUE TITLE
Please change clock notation

### ISSUE THREAD

**Issue by ghost** [ngerritsen/timiks#24]
Change it to WCA plz

**Comment by ngerritsen** [comment]
I’ll look into it

**Comment by ngerritsen** [comment]
@DiscordGod Is this the official WCA notation: `UR6+ DR0+ DL0+ UL5+ U4+ R0+ D6+ L6+ ALL5+ y2 U3+ R5- D0+ L4+ ALL3+ UR DL`?

**Comment by ghost** [comment]
yes

**Comment by ngerritsen** [comment]
@DiscordGod Updated scrambler to generate WCA clock scrambles

Updated in **Build #443**

<img width="757" alt="Screenshot 2019-10-26 at 15 32 18" src="https://user-images.githubusercontent.com/6407496/67620334-ec084280-f805-11e9-9517-d8a66737e410.png">

 https://github.com/ngerritsen/timiks/commit/a099a6efcc75d361581eeb104491540b1e684937
