### ISSUE TITLE
Bug: Stop Timer Error (Unable to be stopped on mobile) 

### ISSUE THREAD

**Issue by bulaxy** [ngerritsen/timiks#27]
Error Found in: 
Device used: iPad Mini 2, iPhone SE 
Settings: Activation delay: non-none

Bug Overview:
If timer is started by holding the time (numbers), the timer will restart no matter where you tap to stop the timer.  (If end the timer tapping on the numbers, will be ended in a loop of timer)

Step to reproduce:

1. Launch Timiks either from website or added to home screen Timiks' icon.
2. Tap on the time (initially 00.000, but any time, this bug will occur)
3. Hold until numbers turn Green
4. Anywhere on the time attempting to stop the timer.

Outcome:
Timer restarted. 

Expected Outcome
Return to home/base page, timer stopped.

Note:
If the first attempt/tap to stop the timer is tapped on the time/number, the time will becomes 00.000 and green indicating the timer is ready for next time. 

Note2: If activation delay set to none, bug will not occur

[Video Link on the error ](https://www.dropbox.com/s/qnnwnibllv8a1le/video-1574835073.mp4?dl=0)
(That video is taken initially, without knowing fully how to reproduce the bug, so a little bit messy)

**Comment by ngerritsen** [comment]
@bulaxy thanks for the elaborate error description! I’ve been able to reproduce the error. It seems to happen when tapping slightly longer when trying to stop the timer. If you tap fast it will not happen. I’ll fix it very soon and let you know!

**Comment by bulaxy** [comment]
@ngerritsen  np! 
I think it might also depends on the device, both my iPad mini 2 and iPhone se are fairly old devices and a bit slow (on my iPad, you can visually see it lag as you attempt to stop the timer), even if I tap as fast as I could, it will still happen.

**Comment by ngerritsen** [comment]
@bulaxy I have a very hard time reproducing the error now :/. My iPad Air 2 and iPhone 6s both cannot get it, though the iPad is pretty slow. Do you still have this error consistently?

**Comment by bulaxy** [comment]
@ngerritsen 
On my iPad mini 2, very consistently, 10/10 tries. Tried clearing everything at the background, still 10/10
On my iPhone Se, a little bit, around 5/10 or so.

**Comment by ngerritsen** [comment]
@bulaxy hmm okay gotta get my hands on a slower device then. My iPad Air 2 should be slower than an iPhone SE though..

**Comment by ngerritsen** [comment]
@bulaxy I think I found the bug, it was actually reproducable on my fast laptop, should be fixed in build #466
