### ISSUE TITLE
Links to PLL algs algdb.net are broken

### ISSUE THREAD

**Issue by nlisgo** [ngerritsen/timiks#29]
To recreate:
- Visit: https://timiks.com/trainer
- Select PLL from the dropdown.
- Click the 'show info' link on the Ub perm (or any other)
- Click the ' View on AlgDb.net' link in the modal box
- You will be taken to http://algdb.net/puzzle/333/oll/ollUb

Expected behaviour:
- You should be taken to http://algdb.net/puzzle/333/pll/ub

**Comment by ngerritsen** [comment]
Fix is on the way!
