### ISSUE TITLE
OLL 6 and 7 are swapped

### ISSUE THREAD

**Issue by tsuharesu** [ngerritsen/timiks#34]
(On the training tab)
When trying to follow the algorithms from a completed cube to arrive on Sune and AntiSune, the algorithms are swapped which makes you fall on the other one. The link to AlgDb show the same image but the algorithm is swapped.

**Comment by ngerritsen** [comment]
Personally I've tried a few, and I do not experience the same thing. For instance, I try this alg, then apply it and it lands on the anti sune:

<img width="872" alt="Screenshot 2020-05-18 at 11 12 29" src="https://user-images.githubusercontent.com/6407496/82195395-8b9f3680-98f8-11ea-8efd-b1f8d72f2798.png">
<img width="1331" alt="Screenshot 2020-05-18 at 11 12 41" src="https://user-images.githubusercontent.com/6407496/82195404-8d68fa00-98f8-11ea-9d9e-e2a28d963b92.png">

Do you have an example of a scramble that lands you on the wrong one?
