### ISSUE TITLE
The TimeTable component is rendered too often

### ISSUE THREAD

**Issue by Jobarion** [ngerritsen/timiks#35]
While debugging the performance of the graph/stats components I noticed that the stats are redrawn (and recalculated) too often:
- When times are removed in the _Timer_ view, TimeTable is rendered onc
- When times are added in the _Timer_ view, TimeTable is rendered twice.
- When the timeframe is changed in the _Archive_ view, TimeTable is rendered twice or thrice. 

Because calculating the stats is a very expensive operation this would be a useful thing to optimize.
I will try to look into that a bit more.

**Comment by ngerritsen** [comment]
Is the stats calculation actually ran twice? Because the selector itself is memoized.

**Comment by Jobarion** [comment]
Yes, the stats calculation ran twice.

**Comment by ngerritsen** [comment]
Cool, well let me know what you find!
