### ISSUE TITLE
Cannot start the timer with inspection

### ISSUE THREAD

**Issue by AkshayRao27** [ngerritsen/timiks#37]
Trying to activate the timer with inspection causes the interface to go blank with a single red bar at the top which reads: "An error occured, reload now." This happens regardless of browser or device. I've tried it with Chrome, Brave and Edge on Windows 10 and Android 10.

The timer seems to work fine without inspection.

**Comment by ngerritsen** [comment]
Will look into it, thanks!

**Comment by ngerritsen** [comment]
A fix is deployed and on the way :D
