### ISSUE TITLE
Averages and Mean of 3

### ISSUE THREAD

**Issue by ghost** [ngerritsen/timiks#4]
<img width="741" alt="Screen Shot 2019-06-06 at 21 08 44" src="https://user-images.githubusercontent.com/40965257/59073880-60663780-889f-11e9-803c-7e539846c8ad.png">

I had some issues with the ao5, ao12 and mo3 metrics (I only did 20 solves, I assume the ao50 and ao100 would also have issues). Not sure what's going on, but I put my times on an excel spreadsheet to confirm and those metrics were really off. I've included an image of my times and the graphic so you can see that if you go and calculate those metrics they really don't match up.

**Comment by ngerritsen** [comment]
Thanks for reporting @BarbaraWar I fixed it in this commit https://github.com/ngerritsen/timiks/commit/957b2f50635c1b3292ad07844e4a0caa93c00914 !
