### ISSUE TITLE
When I stop the timer it sometimes doesn’t count it

### ISSUE THREAD

**Issue by jsjdhdjc** [ngerritsen/timiks#41]
When I stop the timer it says 0.000 and then it doesn’t count in the average. This is especially annoying when I get a good time and it doesn’t get counted

**Comment by ngerritsen** [comment]
I don't know what you mean. The whole timer is not working for you?

**Comment by jsjdhdjc** [comment]
It is working but sometimes it doesn’t count the time and I have to refresh the page so the timer starts working normally again
