### ISSUE TITLE
Please make the timer notify you when there is a Pb ao5, ao25 etc...

### ISSUE THREAD

**Issue by jsjdhdjc** [ngerritsen/timiks#43]
I like when I get a Pb the timer tells me that it is my best time but I would also appreciate if it would do the same for averages. ao5, ao25, etc...

**Comment by ngerritsen** [comment]
Cool idea, the downside is that during the session it will say that a lot then.

**Comment by jsjdhdjc** [comment]
Tbh, I wouldn’t mind that, at least I would know. CS timer does this really well where it doesn’t take up the whole screen but is easily visible so you know that you are doing well

**Comment by jsjdhdjc** [comment]
Are you going to try and do it then??

**Comment by jsjdhdjc** [comment]
Are you?
