### ISSUE TITLE
swap out fontawesome pro for free

### ISSUE THREAD

**Issue by psifertex** [ngerritsen/timiks#47]
From looking through the list of icons currently used, they're all available in the free fontawesome but unfortunately the current system uses fontawesome pro anyway which makes it harder to build/run if you don't have a pro license even though none of the icons need it!

**Comment by ngerritsen** [comment]
I'll check if that's the case, then I'll switch to free to make contributions easier!

**Comment by ngerritsen** [comment]
There are quite some icons not available in the free version of font awesome. I will still try to replace them with free ones but that will take some more time.

**Comment by ngerritsen** [comment]
https://github.com/ngerritsen/timiks/commit/7c45957f89f63f5595c905e36e2475548bf97750

**Comment by psifertex** [comment]
Much appreciated! Thanks for doing this.
