### ISSUE TITLE
Being able to delete big amounts of times in the Archive section.

### ISSUE THREAD

**Issue by ViniAS30** [ngerritsen/timiks#49]
Hi!
The Archive Section is great, there's a lot of great features, specially being able to import times from both Twisty Timer and CSTimer. It has been a great alternative for me to storage my data and visualize it well (the graphs and stats are great). However, there's an issue, I can only remove one time at once. I think a function to erase all stored times or a part of them (by date, or the last x times) would be very handy. Another solution would be allowing multiple sessions. But I believe the former might be easier to accomplish.
A reason for why I'm suggesting this is for example, importing the wrong files, or simply wanting to start a new archive or such. At the moment I'll have to sign in with another account to reset the archive, which isn't much hassle, but I thought this suggestion might be helpful.
Again, I loved what I could do with the data with your timer, it's great work and the interface is great. The Trainer and data storage also seem very nice to me and I'm looking forward to test it! Keep up the great work!

**Comment by ngerritsen** [comment]
Hmm, yeah, interesting use case. I don't know how many times you imported (there are some limitations on the free database I'm using) but maybe being able to delete one whole day at once might already help.
