### ISSUE TITLE
Best mo3 resets after a dnf

### ISSUE THREAD

**Issue by Hubert40** [ngerritsen/timiks#5]
If i input a dnf the stats say that the best mo3 is a dnf.
It seem that it only calculates the best mo3 of all times after the last dnf.
![Timiks-mo3](https://user-images.githubusercontent.com/51487389/59116739-88f83b00-894c-11e9-8983-df8ccdf8bad9.PNG)

**Comment by ngerritsen** [comment]
Will take a look!

**Comment by ngerritsen** [comment]
Fixed it with this commit! https://github.com/ngerritsen/timiks/commit/057f30fc6e1fdab208f670c6ac87170a2f2c0ea9 Thanks for reporting 😃
