### ISSUE TITLE
Show most recent times at the top and older times at the bottom

### ISSUE THREAD

**Issue by jsjdhdjc** [ngerritsen/timiks#50]
Hello, this is not really an issue, but a suggestion. I would really like this timer to show my most recent times at the top of the list so then i dont have to scroll down to see my recent times. I would really appreciate if you could do this because i think that it would help with finding the scrambles for my recent times, as i have lots of times in my session, and scrolling down every time to get a scramble is quite time consuming.

**Comment by pyko** [comment]
Will give this a go!

edit: PR raised - https://github.com/ngerritsen/timiks/pull/54
