### ISSUE TITLE
Times are not truncated to the hundredths as with WCA Standards

### ISSUE THREAD

**Issue by ghost** [ngerritsen/timiks#6]
e.g 12.246 turns to 12.24 and 21.299 turns to 21.29

**Comment by ngerritsen** [comment]
Why do you want the times to truncate? This could be a setting I could implement, to show all times rounded like WCA.

**Comment by ghost** [comment]
it could be a setting because that is the wca standard

**Comment by ngerritsen** [comment]
I changed the app so that the times shown in the results will be WCA rounded, the timer on top will still show the milliseconds.
