### ISSUE TITLE
Attempting to Archive 800 solves does nothing. 

### ISSUE THREAD

**Issue by ConorCuber** [ngerritsen/timiks#9]
It slows down quite a lot, and reloads with no change. I would like to keep as many solves archived as possible. I didn't realise it would be so slow after only 800 solves. Trying to Archive them doesn't work, and I definitely don't want to delete my progress. Beyond this minor complaint, I must say, this is the best speedcubing timer I have ever used. I love it. Thanks so much for your work.

**Comment by ngerritsen** [comment]
Yeah this is because of the limitations of firebase, the free database I'm using behind the scenes. It allows for a maximum batch of 500. I can actually improve this by doing the batch inserts per 500. I will let you know when to try it again.

**Comment by ngerritsen** [comment]
@ConorCuber  Okay I added the batched archive now, if your buildnumber at the bottom is updated to 360 (by refreshing Timiks) you can try again, let me know!
